[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm turbo run build --filter=@paper-market/market-engine..."]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "node apps/market-engine/dist/index.js"
