import { type InferInsertModel, type InferSelectModel } from "drizzle-orm";
export declare const ledgerAccountTypeEnum: import("drizzle-orm/pg-core").PgEnum<["CASH", "MARGIN_BLOCKED", "UNREALIZED_PNL", "REALIZED_PNL", "FEES"]>;
export declare const ledgerReferenceTypeEnum: import("drizzle-orm/pg-core").PgEnum<["TRADE", "ORDER", "LIQUIDATION", "EXPIRY", "ADJUSTMENT", "OPTION_PREMIUM_DEBIT", "OPTION_PREMIUM_CREDIT", "OPTION_MARGIN_BLOCK", "OPTION_MARGIN_RELEASE", "OPTION_REALIZED_PNL"]>;
export declare const ledgerAccounts: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ledger_accounts";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "ledger_accounts";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        userId: import("drizzle-orm/pg-core").PgColumn<{
            name: "userId";
            tableName: "ledger_accounts";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        accountType: import("drizzle-orm/pg-core").PgColumn<{
            name: "accountType";
            tableName: "ledger_accounts";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "CASH" | "MARGIN_BLOCKED" | "UNREALIZED_PNL" | "REALIZED_PNL" | "FEES";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["CASH", "MARGIN_BLOCKED", "UNREALIZED_PNL", "REALIZED_PNL", "FEES"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "ledger_accounts";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const ledgerEntries: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ledger_entries";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        globalSequence: import("drizzle-orm/pg-core").PgColumn<{
            name: "globalSequence";
            tableName: "ledger_entries";
            dataType: "number";
            columnType: "PgBigSerial53";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        debitAccountId: import("drizzle-orm/pg-core").PgColumn<{
            name: "debitAccountId";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        creditAccountId: import("drizzle-orm/pg-core").PgColumn<{
            name: "creditAccountId";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        amount: import("drizzle-orm/pg-core").PgColumn<{
            name: "amount";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        currency: import("drizzle-orm/pg-core").PgColumn<{
            name: "currency";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 3;
        }>;
        referenceType: import("drizzle-orm/pg-core").PgColumn<{
            name: "referenceType";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "TRADE" | "ORDER" | "LIQUIDATION" | "EXPIRY" | "ADJUSTMENT" | "OPTION_PREMIUM_DEBIT" | "OPTION_PREMIUM_CREDIT" | "OPTION_MARGIN_BLOCK" | "OPTION_MARGIN_RELEASE" | "OPTION_REALIZED_PNL";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["TRADE", "ORDER", "LIQUIDATION", "EXPIRY", "ADJUSTMENT", "OPTION_PREMIUM_DEBIT", "OPTION_PREMIUM_CREDIT", "OPTION_MARGIN_BLOCK", "OPTION_MARGIN_RELEASE", "OPTION_REALIZED_PNL"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        referenceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "referenceId";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        idempotencyKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "idempotencyKey";
            tableName: "ledger_entries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "ledger_entries";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const ledgerAccountBalances: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ledger_account_balances";
    schema: undefined;
    columns: {
        accountId: import("drizzle-orm/pg-core").PgColumn<{
            name: "accountId";
            tableName: "ledger_account_balances";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        balance: import("drizzle-orm/pg-core").PgColumn<{
            name: "balance";
            tableName: "ledger_account_balances";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        lastSequence: import("drizzle-orm/pg-core").PgColumn<{
            name: "lastSequence";
            tableName: "ledger_account_balances";
            dataType: "number";
            columnType: "PgBigInt53";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updatedAt";
            tableName: "ledger_account_balances";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type LedgerAccount = InferSelectModel<typeof ledgerAccounts>;
export type NewLedgerAccount = InferInsertModel<typeof ledgerAccounts>;
export type LedgerEntry = InferSelectModel<typeof ledgerEntries>;
export type NewLedgerEntry = InferInsertModel<typeof ledgerEntries>;
export type LedgerAccountBalance = InferSelectModel<typeof ledgerAccountBalances>;
export type NewLedgerAccountBalance = InferInsertModel<typeof ledgerAccountBalances>;
export type LedgerAccountType = typeof ledgerAccountTypeEnum.enumValues[number];
export type LedgerReferenceType = typeof ledgerReferenceTypeEnum.enumValues[number];
//# sourceMappingURL=ledger.schema.d.ts.map