import { type InferInsertModel, type InferSelectModel } from "drizzle-orm";
export declare const writeAheadOperationTypeEnum: import("drizzle-orm/pg-core").PgEnum<["TRADE_EXECUTION", "LEDGER_ENTRY", "LIQUIDATION", "EXPIRY_SETTLEMENT", "MANUAL_ADJUSTMENT"]>;
export declare const writeAheadStatusEnum: import("drizzle-orm/pg-core").PgEnum<["PREPARED", "COMMITTED", "ABORTED"]>;
export declare const writeAheadJournal: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "write_ahead_journal";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "write_ahead_journal";
            dataType: "number";
            columnType: "PgBigSerial53";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        journalId: import("drizzle-orm/pg-core").PgColumn<{
            name: "journalId";
            tableName: "write_ahead_journal";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "write_ahead_journal";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        operationType: import("drizzle-orm/pg-core").PgColumn<{
            name: "operationType";
            tableName: "write_ahead_journal";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "LIQUIDATION" | "TRADE_EXECUTION" | "LEDGER_ENTRY" | "EXPIRY_SETTLEMENT" | "MANUAL_ADJUSTMENT";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["TRADE_EXECUTION", "LEDGER_ENTRY", "LIQUIDATION", "EXPIRY_SETTLEMENT", "MANUAL_ADJUSTMENT"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "write_ahead_journal";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "PREPARED" | "COMMITTED" | "ABORTED";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["PREPARED", "COMMITTED", "ABORTED"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        userId: import("drizzle-orm/pg-core").PgColumn<{
            name: "userId";
            tableName: "write_ahead_journal";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        referenceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "referenceId";
            tableName: "write_ahead_journal";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        payload: import("drizzle-orm/pg-core").PgColumn<{
            name: "payload";
            tableName: "write_ahead_journal";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        checksum: import("drizzle-orm/pg-core").PgColumn<{
            name: "checksum";
            tableName: "write_ahead_journal";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        committedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "committedAt";
            tableName: "write_ahead_journal";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type WriteAheadJournal = InferSelectModel<typeof writeAheadJournal>;
export type NewWriteAheadJournal = InferInsertModel<typeof writeAheadJournal>;
export type WriteAheadOperationType = typeof writeAheadOperationTypeEnum.enumValues[number];
export type WriteAheadStatus = typeof writeAheadStatusEnum.enumValues[number];
//# sourceMappingURL=write_ahead_journal.schema.d.ts.map