import type { ComponentType, SVGProps } from "react";
import {
  MousePointer2,
  Crosshair,
  TrendingUp,
  Minus,
  ArrowUpRight,
  MoveHorizontal,
  MoveVertical,
  Plus,
  SplitSquareVertical,
  Triangle,
  PenTool,
  Ruler,
  Square,
  Circle,
  Type,
  StickyNote,
  Flag,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Target,
  Maximize2,
  Paintbrush,
  Highlighter,
  Tag,
  Navigation,
} from "lucide-react";
import {
  AbcdPatternIcon,
  AnchoredNoteIcon,
  AnchoredTextIcon,
  BarsPatternIcon,
  CalloutIcon,
  CommentIcon,
  CurveIcon,
  CyclicLinesIcon,
  CypherPatternIcon,
  DatePriceRangeIcon,
  DateRangeIcon,
  DisjointChannelIcon,
  DoubleCurveIcon,
  ElliottCorrectionIcon,
  ElliottDoubleComboIcon,
  ElliottImpulseIcon,
  ElliottTriangleIcon,
  ElliottTripleComboIcon,
  EllipseIcon,
  FibChannelIcon,
  FibCirclesIcon,
  FibExtensionIcon,
  FibRetracementIcon,
  FibSpeedArcsIcon,
  FibSpeedFanIcon,
  FibSpiralIcon,
  FibTimeExtensionIcon,
  FibTimeZoneIcon,
  GannBoxIcon,
  GannFanIcon,
  GannSquareFixedIcon,
  GannSquareIcon,
  GhostFeedIcon,
  HeadAndShouldersIcon,
  InsidePitchforkIcon,
  LongPositionIcon,
  ModifiedSchiffPitchforkIcon,
  PitchfanIcon,
  PitchforkIcon,
  PolylineIcon,
  PriceRangeIcon,
  RegressionTrendIcon,
  RotatedRectangleIcon,
  SchiffPitchforkIcon,
  ShortPositionIcon,
  SignpostIcon,
  ThreeDrivesIcon,
  TimeCyclesIcon,
  XabcdPatternIcon,
} from "./icons";

export type ToolIconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const DEFAULT_TOOL_ICON: ToolIconComponent = MousePointer2;

export const TOOL_ICONS: Record<string, ToolIconComponent> = {
  "cursor": MousePointer2,
  "crosshair": Crosshair,
  "select": MousePointer2,
  "trendline": TrendingUp,
  "ray": ArrowUpRight,
  "info-line": Ruler,
  "extended-line": Minus,
  "trend-angle": Navigation,
  "horizontal-line": MoveHorizontal,
  "horizontal-ray": ArrowRight,
  "vertical-line": MoveVertical,
  "cross-line": Plus,
  "parallel-channel": SplitSquareVertical,
  "flat-top-bottom": Maximize2,
  "pitchfork": PitchforkIcon,
  "schiff-pitchfork": SchiffPitchforkIcon,
  "modified-schiff-pitchfork": ModifiedSchiffPitchforkIcon,
  "inside-pitchfork": InsidePitchforkIcon,
  "fib-retracement": FibRetracementIcon,
  "fib-extension": FibExtensionIcon,
  "fib-channel": FibChannelIcon,
  "fib-time-zone": FibTimeZoneIcon,
  "fib-time-extension": FibTimeExtensionIcon,
  "fib-speed-fan": FibSpeedFanIcon,
  "fib-circles": FibCirclesIcon,
  "fib-spiral": FibSpiralIcon,
  "fib-speed-arcs": FibSpeedArcsIcon,
  "pitchfan": PitchfanIcon,
  "gann-box": GannBoxIcon,
  "gann-square-fixed": GannSquareFixedIcon,
  "gann-square": GannSquareIcon,
  "gann-fan": GannFanIcon,
  "xabcd-pattern": XabcdPatternIcon,
  "cypher-pattern": CypherPatternIcon,
  "abcd-pattern": AbcdPatternIcon,
  "head-shoulders": HeadAndShouldersIcon,
  "three-drives-pattern": ThreeDrivesIcon,
  "elliott-impulse": ElliottImpulseIcon,
  "elliott-correction": ElliottCorrectionIcon,
  "elliott-triangle": ElliottTriangleIcon,
  "elliott-double-combo": ElliottDoubleComboIcon,
  "elliott-triple-combo": ElliottTripleComboIcon,
  "cyclic-lines": CyclicLinesIcon,
  "time-cycles": TimeCyclesIcon,
  "long-position": LongPositionIcon,
  "short-position": ShortPositionIcon,
  "forecast": Target,
  "bars-pattern": BarsPatternIcon,
  "ghost-feed": GhostFeedIcon,
  "price-range": PriceRangeIcon,
  "date-range": DateRangeIcon,
  "date-price-range": DatePriceRangeIcon,
  "regression-trend": RegressionTrendIcon,
  "disjoint-channel": DisjointChannelIcon,
  "brush": Paintbrush,
  "highlighter": Highlighter,
  "arrow-marker": ArrowUp,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "rectangle": Square,
  "rotated-rectangle": RotatedRectangleIcon,
  "path": PenTool,
  "circle": Circle,
  "ellipse": EllipseIcon,
  "curve": CurveIcon,
  "double-curve": DoubleCurveIcon,
  "polyline": PolylineIcon,
  "triangle-shape": Triangle,
  "fib-wedge": Triangle,
  "triangle-pattern": Triangle,
  "text": Type,
  "anchored-text": AnchoredTextIcon,
  "note": StickyNote,
  "anchored-note": AnchoredNoteIcon,
  "callout": CalloutIcon,
  "comment": CommentIcon,
  "price-label": Tag,
  "signpost": SignpostIcon,
  "flag-mark": Flag,
};

export const resolveToolIcon = (key: string) => TOOL_ICONS[key] ?? DEFAULT_TOOL_ICON;
